# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vscode-extractor',
                'doc_host': 'https://pavt.github.io',
                'git_url': 'https://github.com/pavt/vscode-extractor',
                'lib_path': 'vscode_extractor'},
  'syms': {}}
